import opentype from 'opentype.js'
import type { FontStyle, StoredFont } from '../types'

const STYLE_WORDS = /(?:[-_\s]+)(thin|hairline|extra\s*light|ultra\s*light|light|regular|book|normal|medium|semi\s*bold|demi\s*bold|bold|extra\s*bold|ultra\s*bold|black|heavy)(?:[-_\s]*(italic|oblique))?$|(?:[-_\s]+)(italic|oblique)$/i

export function inferWeight(value='') { const n=value.toLowerCase().replace(/[\s_-]/g,''); if(/thin|hairline/.test(n))return 100;if(/extralight|ultralight/.test(n))return 200;if(/semibold|demibold/.test(n))return 600;if(/extrabold|ultrabold/.test(n))return 800;if(/black|heavy/.test(n))return 900;if(/light/.test(n))return 300;if(/medium/.test(n))return 500;if(/bold/.test(n))return 700;return 400 }
function pickName(value:unknown){if(!value||typeof value!=='object')return;const names=value as Record<string,string>;return names.en||names['en-US']||Object.values(names).find(Boolean)}
function fallbackNames(filename:string){const base=filename.replace(/\.(ttf|otf|woff2?)$/i,'');const match=base.match(STYLE_WORDS);const familyName=(match?base.slice(0,match.index):base).replace(/[-_]+/g,' ').trim()||base;const subfamilyName=match?.[1]?`${match[1]}${match[2]?` ${match[2]}`:''}`:match?.[3]||'Regular';return{familyName,subfamilyName}}
export async function readFontMetadata(file:Blob,filename:string):Promise<Pick<StoredFont,'familyName'|'subfamilyName'|'fullName'|'weight'|'style'>>{const fallback=fallbackNames(filename);try{const parsed=opentype.parse(await file.arrayBuffer());const familyName=pickName(parsed.names.fontFamily)||fallback.familyName;const subfamilyName=pickName(parsed.names.fontSubfamily)||fallback.subfamilyName;const fullName=pickName(parsed.names.fullName)||`${familyName} ${subfamilyName}`;const osWeight=parsed.tables.os2?.usWeightClass;const weight=typeof osWeight==='number'&&osWeight>=1?osWeight:inferWeight(subfamilyName);const style:FontStyle=/italic|oblique/i.test(subfamilyName)?'italic':'normal';return{familyName,subfamilyName,fullName,weight,style}}catch{return{...fallback,fullName:`${fallback.familyName} ${fallback.subfamilyName}`,weight:inferWeight(fallback.subfamilyName),style:/italic|oblique/i.test(fallback.subfamilyName)?'italic':'normal'}}}
export async function enrichFont(font:StoredFont){if(font.familyName&&font.subfamilyName&&font.weight&&font.style)return font;return{...font,...await readFontMetadata(font.blob,font.filename)}}
