import type { StoredFont, TextStyle } from '../types'
import { fontFamilyFor, loadStoredFont } from './fontLoader'
export function transformText(text:string,mode:TextStyle['caseMode']){if(mode==='upper')return text.toLocaleUpperCase();if(mode==='lower')return text.toLocaleLowerCase();if(mode==='capitalize')return text.replace(/\p{L}+/gu,w=>w.charAt(0).toLocaleUpperCase()+w.slice(1).toLocaleLowerCase());return text}
function rgba(hex:string,o:number){const c=hex.replace('#','');const f=c.length===3?c.split('').map(x=>x+x).join(''):c;const n=parseInt(f,16);return`rgba(${n>>16&255},${n>>8&255},${n&255},${o})`}
function width(ctx:CanvasRenderingContext2D,text:string,s:number){return Array.from(text).reduce((a,c)=>a+ctx.measureText(c).width,0)+Math.max(0,Array.from(text).length-1)*s}
function draw(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,s:number,a:CanvasTextAlign,stroke:boolean){const w=width(ctx,text,s);let p=a==='left'?x:a==='right'?x-w:x-w/2;for(const c of Array.from(text)){const cw=ctx.measureText(c).width;stroke?ctx.strokeText(c,p,y):ctx.fillText(c,p,y);p+=cw+s}}
function round(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(r,h/2,w/2));ctx.fill()}
export async function renderTypography(text:string,font:StoredFont,style:TextStyle,scale=1){
 await loadStoredFont(font);await document.fonts.ready;const value=transformText(text||' ',style.caseMode);const lines=value.split('\n');const curve=lines.length===1?style.curve:0;const p=document.createElement('canvas').getContext('2d')!;const family=fontFamilyFor(font);const rule=`${font.style||'normal'} ${font.weight||400} ${style.fontSize}px "${family}"`;p.font=rule;const widths=lines.map(l=>width(p,l||' ',style.letterSpacing));const widest=Math.max(...widths);const lh=style.fontSize*style.lineHeight;const curveRoom=Math.abs(curve)*.65;const effect=Math.max(style.stroke.enabled?style.stroke.width:0,style.shadow.enabled?style.shadow.blur+Math.abs(style.shadow.x)+Math.abs(style.shadow.y):0);const mx=style.marker.mode==='off'?0:style.marker.paddingX,my=style.marker.mode==='off'?0:style.marker.paddingY;const w=Math.ceil(widest+(style.padding+effect+mx)*2),h=Math.ceil(lines.length*lh+curveRoom+(style.padding+effect+my)*2);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.ceil(w*scale));canvas.height=Math.max(1,Math.ceil(h*scale));const ctx=canvas.getContext('2d')!;ctx.scale(scale,scale);ctx.font=rule;ctx.textBaseline='top';ctx.lineJoin='round';const x=style.alignment==='left'?style.padding+effect+mx:style.alignment==='right'?w-style.padding-effect-mx:w/2;const top=style.padding+effect+my+(curve>0?0:curveRoom);
 if(style.marker.mode!=='off'){ctx.fillStyle=rgba(style.marker.color,style.marker.opacity);lines.forEach((_,i)=>{const lw=widths[i],lx=style.alignment==='left'?x-style.marker.paddingX:style.alignment==='right'?x-lw-style.marker.paddingX:x-lw/2-style.marker.paddingX,ly=top+i*lh-style.marker.paddingY;if(style.marker.mode==='underline')round(ctx,lx,ly+style.fontSize*.72,lw+style.marker.paddingX*2,Math.max(5,style.marker.paddingY*1.2),style.marker.radius);else if(style.marker.mode==='rounded')round(ctx,lx,ly,lw+style.marker.paddingX*2,style.fontSize+style.marker.paddingY*2,style.marker.radius);else ctx.fillRect(lx,ly,lw+style.marker.paddingX*2,style.fontSize+style.marker.paddingY*2)})}
 ctx.fillStyle=style.color;ctx.strokeStyle=style.stroke.color;ctx.lineWidth=style.stroke.width*2;if(style.shadow.enabled){ctx.shadowColor=rgba(style.shadow.color,style.shadow.opacity);ctx.shadowBlur=style.shadow.blur;ctx.shadowOffsetX=style.shadow.x;ctx.shadowOffsetY=style.shadow.y}
 if(curve){const chars=Array.from(lines[0]);const total=widths[0];let cursor=-total/2;const amp=curve*.65;for(const c of chars){const cw=p.measureText(c).width,center=cursor+cw/2,ratio=total?center/(total/2):0,y=top+Math.abs(Math.min(0,amp))+amp*ratio*ratio,angle=Math.atan(total?2*amp*center/Math.pow(total/2,2):0);ctx.save();ctx.translate(w/2+center,y);ctx.rotate(angle);if(style.stroke.enabled)ctx.strokeText(c,-cw/2,0);ctx.fillText(c,-cw/2,0);ctx.restore();cursor+=cw+style.letterSpacing}}else lines.forEach((l,i)=>{const y=top+i*lh;if(style.stroke.enabled)draw(ctx,l,x,y,style.letterSpacing,style.alignment,true);draw(ctx,l,x,y,style.letterSpacing,style.alignment,false)});return canvas
}
export const canvasToBlob=(canvas:HTMLCanvasElement)=>new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('PNG creation failed')),'image/png'))
export function dataUrlToBlob(url:string){const [head,data]=url.split(','),bin=atob(data),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:head.match(/:(.*?);/)?.[1]||'image/png'})}
export function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
